name: ecom
description: "A Flutter real project of ecommerce"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 #----------------------------- packages----------------------------#
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  go_router: ^14.2.3
  shared_preferences: ^2.2.3
  iconsax: ^0.0.8
  http: ^1.2.2
  dio: ^5.6.0
  logger: ^2.4.0
  fluttertoast: ^8.2.8
  mailer: ^6.1.2
  internet_connection_checker: ^1.0.0+1
  carousel_slider: ^5.0.0
  autoscale_tabbarview: ^1.0.2
  image_picker: ^1.1.2
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  #-------------------------- assets -------------------------------#
  #---------------------- image ------------------------------------#
  assets:
    - assets/
    - assets/intro/
    - assets/splash/

  #--------------------------------------- font ----------------------------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800


flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/splash/splash.png
  image_dark: assets/splash/splash.png

  android_12:
    color: "#ffffff"
    color_dark: "#272727"
    image: assets/splash/splash.png
    image_dark: assets/splash/splash.png

  web: false